# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cpi.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "cpi.BaseRequest" do
    optional :type, :string, 1
    optional :stemcell_api_version, :int32, 2
    optional :director_uuid, :string, 3
    optional :properties, :bytes, 4
  end
  add_message "cpi.BaseResponse" do
    optional :error, :string, 1
    optional :log, :string, 2
  end
  add_message "cpi.InfoResponse" do
    optional :base, :message, 1, "cpi.BaseResponse"
    optional :api_version, :int32, 2
    repeated :stemcell_formats, :string, 3
  end
end

module Cpi
  BaseRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("cpi.BaseRequest").msgclass
  BaseResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("cpi.BaseResponse").msgclass
  InfoResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("cpi.InfoResponse").msgclass
end
