# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: cpi.proto for package 'cpi'

require 'grpc'
require 'cpi_pb'

module Cpi
  module CPI
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'cpi.CPI'

      rpc :Info, Request, Response
      rpc :CreateVM, Request, Response
    end

    Stub = Service.rpc_stub_class
  end
end
